server:
 port: 0
spring:
  application:
    name: test
  datasource:
    url: jdbc:postgresql://localhost:5432/Amzur
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true